# This file was auto-generated by Fern from our API Definition.

from ...core.api_error import ApiError
from ..types.invalid_api_key_body import InvalidApiKeyBody


class InvalidApiKey(ApiError):
    def __init__(self, body: InvalidApiKeyBody):
        super().__init__(status_code=401, body=body)
