# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Contact(UniversalBaseModel):
    name: typing.Optional[str] = None
    company: typing.Optional[str] = None
    street: typing.Optional[str] = None
    city: typing.Optional[str] = None
    state: typing.Optional[str] = None
    zip_code: typing.Optional[str] = None
    country_name: typing.Optional[str] = None
    country_code: typing.Optional[str] = None
    email_address: typing.Optional[str] = None
    phone: typing.Optional[str] = None
    fax: typing.Optional[str] = None
    mailing_address: typing.Optional[str] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
