# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .database_updates import DatabaseUpdates
from .dataset_status import DatasetStatus
from .newly import Newly


class FileStatusApiResponse(UniversalBaseModel):
    newly: typing.Optional[Newly] = None
    cleaned_expired: typing.Optional[DatasetStatus] = None
    expired: typing.Optional[DatasetStatus] = None
    dropped: typing.Optional[DatasetStatus] = None
    database_updates: typing.Optional[DatabaseUpdates] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
