# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .dataset_status import DatasetStatus


class UpdateFrequency(UniversalBaseModel):
    daily: typing.Optional[DatasetStatus] = None
    weekly: typing.Optional[DatasetStatus] = None
    monthly: typing.Optional[DatasetStatus] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
