# This file was auto-generated by Fern from our API Definition.

from __future__ import annotations


class WhoisfreaksApiEnvironment:
    PRODUCTION: WhoisfreaksApiEnvironment

    def __init__(self, *, apis: str, files: str):
        self.apis = apis
        self.files = files


WhoisfreaksApiEnvironment.PRODUCTION = WhoisfreaksApiEnvironment(
    apis="https://api.whoisfreaks.com", files="https://files.whoisfreaks.com"
)
